#!/usr/bin/env python3
import sys
try:
    sys.path.insert(0, './src')
    from SQLite import SQLite as DB
    import Logger, Cmdline, Configuration, OSMDB
except ImportError as e:
    print(str(e), file=sys.stderr)
    print('Cannot find the module(s) listed above. Exiting.', file=sys.stderr)
    sys.exit(1)

short_options = {'--update'    : '-u',
                 '--network'   : '-n',
                 '--list'      : '-l'}
cmdline = Cmdline.Cmdline(sys.argv, short_options)
configuration = Configuration.Configuration()
db = DB(configuration.configuration)
logger = Logger.Logger()
logger.setLogfile(configuration.configuration['log_file'])
osmdb = OSMDB.OSMDB(configuration.configuration, db, logger)

if cmdline.option('u') in ['host','hosts']:
    ping_delays = osmdb.pingHosts(cmdline.option('n'))
    osmdb.updateHosts(ping_delays)

if cmdline.option('l') in ['host','hosts']:
    osmdb.listHosts()
